# menu
main:
  - identifier: posts
    name: posts
    pre: ""
    url: "/posts/"
    weight: 1
  - identifier: repository
    name: repository
    pre: ""
    url: "https://github.com/peaceiris/hugo-theme-iris"
    weight: 2
    params:
      target: "_blank"
      rel: "noopener noreferrer"
  - identifier: author
    name: author
    pre: ""
    url: "https://peaceiris.com"
    weight: 3
    params:
      target: "_blank"
      rel: "noopener noreferrer"
  - identifier: hugo-site
    name: hugo
    pre: ""
    url: "https://gohugo.io/"
    weight: 4
    params:
      target: "_blank"
      rel: "noopener noreferrer"
  - identifier: rss
    name: rss
    pre: ""
    url: "/index.xml"
    weight: 5
