repo:
  URL: "https://github.com/peaceiris/hugo-theme-iris"
  branch: main
  contentDir: exampleSite/content

themeColor: "#ffffff" # smart phone's browser tab color

footer:
  copyright:
    name: peaceiris
    link: "https://peaceiris.com/"

icon:
  favicon: /favicon/favicon64.ico
  x180: /favicon/apple-icon-180x180.jpg
  mstile: /favicon/ms-icon-150x150.jpg

# disableBreadcrumbNavigation: true
