name: Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
  schedule:
    - cron: "13 13 * * *"

jobs:
  skipci:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "[Skip CI] ${{ contains(github.event.head_commit.message, '[skip ci]') }}"

  deploy:
    runs-on: ubuntu-18.04
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
      - uses: actions/checkout@v2

      - name: Read .env
        id: hugo_version
        run: |
          . ./.env
          echo "::set-output name=hugo_version::${HUGO_VERSION}"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "${{ steps.hugo_version.outputs.hugo_version }}"
          extended: true

      - name: Build
        working-directory: ./exampleSite
        run: |
          export BASE_URL="https://hugothemeiris.peaceiris.app"
          make data
          hugo --gc --minify --themesDir ../ --layoutDir ../layouts --baseURL "${BASE_URL}"
          wget -O ./public/report.html "${BASE_URL}/report.html" || true

      - name: Deploy (script mode)
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./exampleSite/public
          SCRIPT_MODE: true
        run: |
          wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2/entrypoint.sh
          bash ./entrypoint.sh

    # - name: Deploy
    #   # uses: peaceiris/actions-gh-pages@v2
    #   uses: docker://peaceiris/gh-pages:v2
    #   env:
    #     # ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    #     PUBLISH_BRANCH: gh-pages
    #     PUBLISH_DIR: ./exampleSite/public
