name: Lighthouse

on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"

jobs:
  lighthouse:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "12.x"

      - name: Install lighthouse
        run: sudo npm i -g lighthouse

      - name: Run lighthouse
        run: |
          lighthouse \
            --chrome-flags="--headless" \
            --output html --output-path ./report.html \
            'https://hugothemeiris.peaceiris.app'

      - name: Upload result
        uses: actions/upload-artifact@v2.2.2
        with:
          name: lighthouse-report
          path: report.html

      - name: Prepare assets
        run: |
          mkdir ./public
          cp ./report.html ./public/report.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
