name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "*.md"

jobs:
  skipci:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "[skip ci] ${{ contains(github.event.head_commit.message, '[skip ci]') }}"

  test:
    runs-on: ubuntu-18.04
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
      - uses: actions/checkout@v2

      - name: Read .env
        id: hugo_version
        run: |
          . ./.env
          echo "::set-output name=hugo_version::${HUGO_VERSION}"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "${{ steps.hugo_version.outputs.hugo_version }}"
          extended: true

      - name: Build Testing
        run: make buildgha

  test-docker:
    runs-on: ubuntu-18.04
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
      - uses: actions/checkout@v2

      - name: Build Testing with Docker
        run: make build

  test-setup:
    runs-on: ubuntu-18.04
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
      - uses: actions/checkout@v2

      - name: Read .env
        id: hugo_version
        run: |
          . ./.env
          echo "::set-output name=hugo_version::${HUGO_VERSION}"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "${{ steps.hugo_version.outputs.hugo_version }}"
          extended: true

      - name: Setup Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Create a new Hugo project
        run: |
          cd ~
          mkdir ./homepage
          wget https://raw.githubusercontent.com/peaceiris/hugo-theme-iris/master/scripts/setup.sh
          bash ./setup.sh ./homepage
          cd ./homepage
          hugo
